package com.huxm.demo.demo1.dao.auto;

import com.huxm.demo.demo1.entity.auto.Request;
import com.huxm.demo.demo1.entity.auto.RequestExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RequestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S1.REQUEST
     *
     * @mbg.generated Thu May 17 15:56:52 CST 2018
     */
    long countByExample(RequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S1.REQUEST
     *
     * @mbg.generated Thu May 17 15:56:52 CST 2018
     */
    int deleteByExample(RequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S1.REQUEST
     *
     * @mbg.generated Thu May 17 15:56:52 CST 2018
     */
    int insert(Request record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S1.REQUEST
     *
     * @mbg.generated Thu May 17 15:56:52 CST 2018
     */
    int insertSelective(Request record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S1.REQUEST
     *
     * @mbg.generated Thu May 17 15:56:52 CST 2018
     */
    List<Request> selectByExample(RequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S1.REQUEST
     *
     * @mbg.generated Thu May 17 15:56:52 CST 2018
     */
    int updateByExampleSelective(@Param("record") Request record, @Param("example") RequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S1.REQUEST
     *
     * @mbg.generated Thu May 17 15:56:52 CST 2018
     */
    int updateByExample(@Param("record") Request record, @Param("example") RequestExample example);
}