package com.huxm.demo.demo1.dao.auto;

import com.huxm.demo.demo1.entity.auto.Request;
import com.huxm.demo.demo1.entity.auto.RequestExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface RequestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request
     *
     * @mbg.generated Sat May 19 23:47:21 CST 2018
     */
    long countByExample(RequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request
     *
     * @mbg.generated Sat May 19 23:47:21 CST 2018
     */
    int deleteByExample(RequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request
     *
     * @mbg.generated Sat May 19 23:47:21 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request
     *
     * @mbg.generated Sat May 19 23:47:21 CST 2018
     */
    int insert(Request record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request
     *
     * @mbg.generated Sat May 19 23:47:21 CST 2018
     */
    int insertSelective(Request record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request
     *
     * @mbg.generated Sat May 19 23:47:21 CST 2018
     */
    List<Request> selectByExample(RequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request
     *
     * @mbg.generated Sat May 19 23:47:21 CST 2018
     */
    Request selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request
     *
     * @mbg.generated Sat May 19 23:47:21 CST 2018
     */
    int updateByExampleSelective(@Param("record") Request record, @Param("example") RequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request
     *
     * @mbg.generated Sat May 19 23:47:21 CST 2018
     */
    int updateByExample(@Param("record") Request record, @Param("example") RequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request
     *
     * @mbg.generated Sat May 19 23:47:21 CST 2018
     */
    int updateByPrimaryKeySelective(Request record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request
     *
     * @mbg.generated Sat May 19 23:47:21 CST 2018
     */
    int updateByPrimaryKey(Request record);
}