package com.huxm.demo.demo1.entity.auto;

public class Request {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column S1.REQUEST.ID
     *
     * @mbg.generated Thu May 17 15:56:52 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column S1.REQUEST.CREATEOR
     *
     * @mbg.generated Thu May 17 15:56:52 CST 2018
     */
    private Integer createor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column S1.REQUEST.REVIEWER
     *
     * @mbg.generated Thu May 17 15:56:52 CST 2018
     */
    private Integer reviewer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column S1.REQUEST.STATUS
     *
     * @mbg.generated Thu May 17 15:56:52 CST 2018
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S1.REQUEST.ID
     *
     * @return the value of S1.REQUEST.ID
     *
     * @mbg.generated Thu May 17 15:56:52 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S1.REQUEST.ID
     *
     * @param id the value for S1.REQUEST.ID
     *
     * @mbg.generated Thu May 17 15:56:52 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S1.REQUEST.CREATEOR
     *
     * @return the value of S1.REQUEST.CREATEOR
     *
     * @mbg.generated Thu May 17 15:56:52 CST 2018
     */
    public Integer getCreateor() {
        return createor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S1.REQUEST.CREATEOR
     *
     * @param createor the value for S1.REQUEST.CREATEOR
     *
     * @mbg.generated Thu May 17 15:56:52 CST 2018
     */
    public void setCreateor(Integer createor) {
        this.createor = createor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S1.REQUEST.REVIEWER
     *
     * @return the value of S1.REQUEST.REVIEWER
     *
     * @mbg.generated Thu May 17 15:56:52 CST 2018
     */
    public Integer getReviewer() {
        return reviewer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S1.REQUEST.REVIEWER
     *
     * @param reviewer the value for S1.REQUEST.REVIEWER
     *
     * @mbg.generated Thu May 17 15:56:52 CST 2018
     */
    public void setReviewer(Integer reviewer) {
        this.reviewer = reviewer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S1.REQUEST.STATUS
     *
     * @return the value of S1.REQUEST.STATUS
     *
     * @mbg.generated Thu May 17 15:56:52 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S1.REQUEST.STATUS
     *
     * @param status the value for S1.REQUEST.STATUS
     *
     * @mbg.generated Thu May 17 15:56:52 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }
}