package com.huxm.demo.demo1.entity.auto;

public class Request {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column request.id
     *
     * @mbg.generated Sat May 19 23:47:21 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column request.creatorId
     *
     * @mbg.generated Sat May 19 23:47:21 CST 2018
     */
    private Integer creatorid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column request.reviewerId
     *
     * @mbg.generated Sat May 19 23:47:21 CST 2018
     */
    private Integer reviewerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column request.status
     *
     * @mbg.generated Sat May 19 23:47:21 CST 2018
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column request.id
     *
     * @return the value of request.id
     *
     * @mbg.generated Sat May 19 23:47:21 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column request.id
     *
     * @param id the value for request.id
     *
     * @mbg.generated Sat May 19 23:47:21 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column request.creatorId
     *
     * @return the value of request.creatorId
     *
     * @mbg.generated Sat May 19 23:47:21 CST 2018
     */
    public Integer getCreatorid() {
        return creatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column request.creatorId
     *
     * @param creatorid the value for request.creatorId
     *
     * @mbg.generated Sat May 19 23:47:21 CST 2018
     */
    public void setCreatorid(Integer creatorid) {
        this.creatorid = creatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column request.reviewerId
     *
     * @return the value of request.reviewerId
     *
     * @mbg.generated Sat May 19 23:47:21 CST 2018
     */
    public Integer getReviewerid() {
        return reviewerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column request.reviewerId
     *
     * @param reviewerid the value for request.reviewerId
     *
     * @mbg.generated Sat May 19 23:47:21 CST 2018
     */
    public void setReviewerid(Integer reviewerid) {
        this.reviewerid = reviewerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column request.status
     *
     * @return the value of request.status
     *
     * @mbg.generated Sat May 19 23:47:21 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column request.status
     *
     * @param status the value for request.status
     *
     * @mbg.generated Sat May 19 23:47:21 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

	@Override
	public String toString() {
		return "Request [id=" + id + ", creatorid=" + creatorid + ", reviewerid=" + reviewerid + ", status=" + status
				+ "]";
	}
    
    
}